name: Check formatting

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run gofmt
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '1.25.4'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Golang
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run gofmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go files not properly formatted."
            echo "Rune 'gofmt -w .' to fix."
            exit 1
          fi